const { execSync } = require("child_process");

console.log("👑 HARDLINE AI EXECUTIVE BRAIN ONLINE");

/*
====================================
EXECUTIVE CONFIG
====================================
*/

const SITE = "https://hardlineprivacy.com";

let workflows = [];

/*
====================================
SAFE COMMAND RUNNER
====================================
*/

function run(cmd) {
  try {
    console.log(`▶ ${cmd}`);
    return execSync(cmd, {
      encoding: "utf8",
      stdio: "pipe"
    });
  } catch (err) {
    console.log("Command failed:", err.message);
    return "";
  }
}

/*
====================================
DISCOVER ORGANIZATION CAPABILITIES
====================================
*/

function discoverWorkflows() {

  console.log("🧠 Mapping Hardline divisions...");

  const list = run("gh workflow list --json name,path");

  if (!list) return;

  const parsed = JSON.parse(list);

  workflows = parsed
    .filter(wf =>
      !wf.path.includes("executive.yml")
    )
    .map(wf => wf.name);

  console.log("✅ Divisions Found:", workflows);
}

/*
====================================
EXECUTIVE COMMAND
====================================
*/

function dispatch(workflow) {
  console.log(`🚀 Executive activating → ${workflow}`);
  run(`gh workflow run "${workflow}"`);
}

/*
====================================
BUSINESS HEALTH CHECK
====================================
*/

function analyzeWebsite() {

  console.log("🌐 Checking revenue surface...");

  const result = run(`curl -Is ${SITE}`);

  if (!result.includes("200")) {
    createIssue("🚨 Website unavailable — revenue risk");
  } else {
    console.log("✅ Website online");
  }
}

function analyzeRepo() {

  console.log("🔎 Checking operational health...");

  const status = run("git status --porcelain");

  if (status.trim().length > 0) {
    createIssue("⚠ Repository changes pending review");
  }
}

/*
====================================
EXECUTIVE DECISION ENGINE
====================================
*/

function executiveDecisions() {

  console.log("💰 Running Executive Decisions");

  const actions = [
    "node ai/autonomous-growth-brain.js",
    "node ai/autonomous-revenue-brain.js",
    "node ai/executive-intelligence.js"
  ];

  actions.forEach(run);
}

/*
====================================
AUTONOMOUS MANAGEMENT
====================================
*/

function createIssue(title) {

  run(
    `gh issue create --title "${title}" --body "Generated by Hardline AI Executive Brain."`
  );
}

/*
====================================
EXECUTIVE LOOP
====================================
*/

function runExecutiveCycle() {

  console.log("👑 EXECUTIVE CYCLE STARTED");

  discoverWorkflows();

  analyzeWebsite();
  analyzeRepo();

  workflows.forEach(dispatch);

  executiveDecisions();

  console.log("✅ EXECUTIVE CYCLE COMPLETE");
}

runExecutiveCycle();
