const { execSync } = require("child_process");
const fs = require("fs");

console.log("👑 HARDLINE TRUE AI EXECUTIVE ONLINE");

/*
====================================
CONFIG
====================================
*/

const SITE = "https://hardlineprivacy.com";

let workflows = [];

/*
====================================
SAFE COMMAND RUNNER
====================================
*/

function run(cmd) {
  console.log(`▶ ${cmd}`);
  return execSync(cmd, {
    encoding: "utf8",
    stdio: "pipe"
  });
}

/*
====================================
WORKFLOW DISCOVERY
====================================
*/

function discoverWorkflows() {
  console.log("🧠 Discovering workflows...");

  const list = run("gh workflow list --json name,path");
  const parsed = JSON.parse(list);

  workflows = parsed
    .filter(wf => !wf.path.includes("operator.yml"))
    .map(wf => wf.name);

  console.log("✅ Found workflows:", workflows);
}

function dispatch(workflow) {
  console.log(`🚀 Executing division → ${workflow}`);
  run(`gh workflow run "${workflow}"`);
}

/*
====================================
EXECUTIVE ANALYSIS
====================================
*/

function analyzeWebsite() {
  console.log("🌐 Checking revenue surface...");

  try {
    run(`curl -Is ${SITE}`);
    console.log("✅ Website reachable");
  } catch {
    createIssue("🚨 Website unavailable — revenue risk");
  }
}

function analyzeRepoHealth() {
  console.log("🔎 Checking repo health...");

  const status = run("git status --porcelain");

  if (status.trim().length > 0) {
    createIssue("⚠ Repository changes detected");
  }
}

/*
====================================
AUTONOMOUS MANAGEMENT
====================================
*/

function createIssue(title) {
  console.log(`📌 Creating Issue → ${title}`);

  run(
    `gh issue create --title "${title}" --body "Created automatically by Hardline Executive AI."`
  );
}

/*
====================================
REVENUE ENGINE
====================================
*/

function revenueDecisions() {
  console.log("💰 Executive Revenue Optimization");

  const improvements = [
    {
      title: "Improve homepage CTA",
      file: "index.html",
      change: "<!-- Executive AI: Stronger CTA placement -->"
    },
    {
      title: "Add trust signals",
      file: "index.html",
      change: "<!-- Executive AI: testimonials + guarantees -->"
    },
    {
      title: "Clarify pricing",
      file: "pricing.html",
      change: "<!-- Executive AI: simplified pricing tiers -->"
    }
  ];

  improvements.forEach(improvement => {
    try {

      fs.appendFileSync(
        improvement.file,
        `\n${improvement.change}\n`
      );

      run('git config user.name "Hardline Executive AI"');
      run('git config user.email "ai@hardlineprivacy.com"');

      const branch = `executive-${Date.now()}`;

      run(`git checkout -b ${branch}`);
      run("git add .");
      run(`git commit -m "Executive Optimization: ${improvement.title}"`);
      run(`git push origin ${branch}`);

      run(
        `gh pr create --title "Executive Optimization: ${improvement.title}" --body "Autonomous revenue improvement generated by Executive AI."`
      );

      console.log("✅ Improvement proposed");

    } catch (err) {
      console.log("Skipped improvement:", err.message);
    }
  });
}

/*
====================================
EXECUTIVE COMMAND LOOP
====================================
*/

function runExecutiveCycle() {
  console.log("👑 EXECUTIVE CYCLE STARTED");

  discoverWorkflows();
  analyzeWebsite();
  analyzeRepoHealth();

  workflows.forEach(dispatch);

  revenueDecisions();

  console.log("✅ EXECUTIVE CYCLE COMPLETE");
}

runExecutiveCycle();
