const { execSync } = require("child_process");
const fs = require("fs");

console.log("💰 HARDLINE REVENUE ENGINE ONLINE");

function run(cmd){
return execSync(cmd,{encoding:"utf8"});
}

# /*

# CONTENT ACQUISITION ENGINE

*/

const articles = [
"How To Remove Your Address From Google",
"Why Your Phone Number Is Public Online",
"Data Broker Sites Explained",
"How Criminals Find Home Addresses Online",
"People Search Sites You Should Remove Yourself From"
];

function createBlogPost(title){

const slug = title
.toLowerCase()
.replace(/[^a-z0-9]+/g,"-");

const file = `blog/${slug}.html`;

if(fs.existsSync(file)) return;

console.log("📝 Creating article:",title);

const content = `

<h1>${title}</h1>

<p>Hardline Privacy helps families remove personal information
from data broker and people-search websites.</p>

<p>Run a free exposure scan:
<a href="/scan">https://hardlineprivacy.com/scan</a></p>
`;

fs.writeFileSync(file,content);

run('git config user.name "Hardline Revenue AI"');
run('git config user.email "[ai@hardlineprivacy.com](mailto:ai@hardlineprivacy.com)"');

run(`git checkout -b revenue-${Date.now()}`);
run("git add .");
run(`git commit -m "Revenue Engine: ${title}"`);
run("git push origin HEAD");

run(`     gh pr create \     --title "Revenue Content: ${title}" \     --body "Automated SEO revenue article generated by Hardline Revenue Engine."
  `);
}

# /*

# SEO DOMINATION LOOP

*/

function runRevenueEngine(){

articles.forEach(createBlogPost);

console.log("✅ Revenue expansion complete");
}

runRevenueEngine();
